In [22]:
from scipy import io
import numpy as np

In [23]:
X = io.loadmat('origin_X.mat')
Y = io.loadmat('origin_Y.mat')

In [24]:
Data_X = X['X']
Data_Y = Y['Y']

In [25]:
import pandas as pd

In [26]:
Data_X = pd.DataFrame(Data_X)
Data_Y = pd.DataFrame(Data_Y)

In [27]:
Label = pd.DataFrame(-np.ones(np.shape(Data_Y)))

In [28]:
Label.loc[Data_Y[0] != 5] = 1

In [29]:
import math

In [30]:
num_folds = 10
subset_size = math.trunc(len(Data_X)/num_folds)

In [31]:
subset_size

5920

In [32]:
Data_X = np.array(Data_X)
Label = np.array(Label)

In [33]:
from sklearn.model_selection import KFold

In [34]:
kf = KFold(n_splits=10)

In [35]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [36]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [37]:
from sklearn.metrics import confusion_matrix

In [38]:
confu_mat = list()

In [39]:
for train_index, test_index in kf.split(Data_X):
    X_train, X_test = Data_X[train_index], Data_X[test_index]
    y_train, y_test = Label[train_index], Label[test_index]
    y_train = np.ravel(y_train)
    
    clf = QuadraticDiscriminantAnalysis()
    clf.fit(X_train, y_train)
    
    y_pred = clf.predict(X_test)
    score  = clf.score(X_test, y_test)
    print(score)
    
    conmat = confusion_matrix(y_test, y_pred)
    confu_mat.append(conmat)
    print(conmat)

0.9003546698192872
[[5320   36]
 [ 554   11]]
0.9108258740077689
[[5388   23]
 [ 505    5]]
0.9032258064516129
[[5341   35]
 [ 538    7]]
0.900523560209424
[[5324   42]
 [ 547    8]]
0.9072791758148961
[[5365   36]
 [ 513    7]]
0.90625
[[5360   25]
 [ 530    5]]
0.8993243243243243
[[5320   40]
 [ 556    4]]
0.9070945945945946
[[5357   43]
 [ 507   13]]
0.9054054054054054
[[5354   26]
 [ 534    6]]
0.9018581081081081
[[5332   38]
 [ 543    7]]


In [40]:
sum_confu = sum(confu_mat)
specificity = sum_confu[0,0] / (sum_confu[0,0]+sum_confu[0,1])
sensitivity = sum_confu[1,1] / (sum_confu[1,1]+sum_confu[1,0])

In [41]:
sum_confu

array([[53461,   344],
       [ 5327,    73]])

In [42]:
print('specificity: {0}, sensitivity: {1}'.format(specificity,sensitivity))

specificity: 0.9936065421429235, sensitivity: 0.013518518518518518
