In [17]:
from scipy import io
import numpy as np

In [18]:
X = io.loadmat('origin_X.mat')
Y = io.loadmat('origin_Y.mat')

In [19]:
Data_X = X['X']
Data_Y = Y['Y']

In [20]:
import pandas as pd

In [21]:
Data_X = pd.DataFrame(Data_X)
Data_Y = pd.DataFrame(Data_Y)

In [22]:
Label = pd.DataFrame(-np.ones(np.shape(Data_Y)))

In [23]:
Label.loc[Data_Y[0] != 5] = 1

In [24]:
import math

In [25]:
num_folds = 10
subset_size = math.trunc(len(Data_X)/num_folds)

In [26]:
subset_size

5920

In [27]:
Data_X = np.array(Data_X)
Label = np.array(Label)

In [28]:
from sklearn.model_selection import KFold

In [29]:
kf = KFold(n_splits=10)

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
from sklearn.metrics import confusion_matrix

In [45]:
confu_mat = list()

In [46]:
for train_index, test_index in kf.split(Data_X):
    X_train, X_test = Data_X[train_index], Data_X[test_index]
    y_train, y_test = Label[train_index], Label[test_index]
    y_train = np.ravel(y_train)
    
    clf = RandomForestClassifier()
    clf.fit(X_train, y_train)
    
    y_pred = clf.predict(X_test)
    score  = clf.score(X_test, y_test)
    print(score)
    
    conmat = confusion_matrix(y_test, y_pred)
    confu_mat.append(conmat)
    print(conmat)

0.9994933288295896
[[5356    0]
 [   3  562]]
1.0
[[5411    0]
 [   0  510]]
0.9996622192197264
[[5376    0]
 [   2  543]]
0.9994933288295896
[[5366    0]
 [   3  552]]
0.9998311096098632
[[5401    0]
 [   1  519]]
0.9998310810810811
[[5385    0]
 [   1  534]]
0.9996621621621622
[[5360    0]
 [   2  558]]
0.9994932432432433
[[5400    0]
 [   3  517]]
0.9994932432432433
[[5380    0]
 [   3  537]]
0.9998310810810811
[[5370    0]
 [   1  549]]


In [50]:
sum_confu = sum(confu_mat)

In [52]:
sum_confu[0,0]

53805

In [53]:
specificity = sum_confu[0,0] / (sum_confu[0,0]+sum_confu[0,1])

In [55]:
sensitivity = sum_confu[1,1] / (sum_confu[1,1]+sum_confu[1,0])

In [56]:
print('specificity: {0}, sensitivity: {1}'.format(specificity,sensitivity))

specificity: 1.0, sensitivity: 0.9964814814814815
