In [1]:
import numpy as np

## Softmax overflow 해결
### 지수함수를 사용하는 softmax는 아주 큰 값을 내뱉으므로, nan값이 나올 수 있다. C라는 임의의 정수를 분자와 분모 양쪽에 곱하고 지수함수 exp() 안으로 옮겨 logC로 만든다.

In [2]:
a = np.array([1010, 1000, 990])

In [3]:
np.exp(a) / np.sum(np.exp(a))

C:\Users\jhpark\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([nan, nan, nan])

In [5]:
c = np.max(a) # c = 1010 (최댓값)

In [6]:
a - c

array([  0, -10, -20])

In [7]:
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

#### 입력 신호 중 최댓값 (이 예에서는 c)을 빼주면 올바르게 계산 가능, 안해줬을 때는 nan값으로 나옴, 또한 sum이 1이기 때문에 확률 값으로 봄. y = exp(x)가 단조 증가 함수이기 때문에 대소관계도 변하지 않는다.

In [15]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [16]:
a = np.array([0.3, 2.9, 4.0])

In [17]:
y = softmax(a)

In [18]:
print(y)

[0.01821127 0.24519181 0.73659691]


In [19]:
np.sum(y)

1.0