In [1]:
import numpy as np

In [2]:
test_array = np.array(["1","4",5,6], float)
test_array

array([1., 4., 5., 6.])

In [4]:
test_array.dtype

dtype('float64')

In [5]:
test_array.shape

(4,)

In [6]:
np.array([["1","4",5,6]], float).shape

(1, 4)

In [8]:
# 3rd order tenser일 경우 (4,3,4)라는 shape에서 첫번째는 깊이, 두번째는 row, 세번째는 column을 뜻한다
# ndim : dimension 수
# size : data 개수

In [9]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [10]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [12]:
# -1을 해줄 경우 알아서 지정해줌
np.array(test_matrix).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [13]:
# 다차원 array를 1차원 array로 변환
# (2,2,4) > (16,)
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8])

In [16]:
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [15]:
np.arange(0,5,0.5) # floating point도 표시 가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [19]:
np.eye(3,5,k=2) # k > start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [21]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.20764846, 0.8106969 , 0.56105277, 0.10708332, 0.83127086],
       [0.6701902 , 0.44380597, 0.50667485, 0.01092855, 0.88066748]])

In [22]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
test_array.sum(axis=1), test_array.sum(axis=0) # axis = 1은 row를 기준으로 더해, axis = 0은 column을 기준으로 더해

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [25]:
# np.where은 조건을 만족하는 것이 어디 있는지를 알려줌

In [26]:
test_array = np.array([1,4,0,2,3,8,9,7], float)

In [27]:
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [28]:
test_array[test_array>3]

array([4., 8., 9., 7.])

In [29]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])