In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor

In [75]:
dataset=np.loadtxt("100singletrack_1.csv", delimiter=",")
x=dataset[:,0:3]
y=dataset[:,3:5]

scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()
print(scaler_x.fit(x))
xscale=scaler_x.transform(x)
print(scaler_y.fit(y))
yscale=scaler_y.transform(y)

MinMaxScaler(copy=True, feature_range=(0, 1))
MinMaxScaler(copy=True, feature_range=(0, 1))


In [76]:
print(x)

[[350.    5.5   4. ]
 [350.    5.5   6. ]
 [350.    5.5   8. ]
 [350.    4.5   6. ]
 [350.    5.5   9. ]
 [350.    3.5   4. ]
 [350.    6.5   9. ]
 [350.    4.5   7. ]
 [350.    3.5   5. ]
 [350.    6.5   6. ]
 [350.    3.5   7. ]
 [350.    3.5   8. ]
 [350.    8.5   9. ]
 [350.    3.5   9. ]
 [350.    7.5   9. ]
 [350.    7.5   7. ]
 [350.    7.5   8. ]
 [350.    7.5   6. ]
 [350.    8.5   5. ]
 [350.    8.5   7. ]
 [450.    3.5   4. ]
 [450.    3.5   7. ]
 [450.    4.5   9. ]
 [450.    5.5   9. ]
 [450.    3.5   8. ]
 [450.    5.5   4. ]
 [450.    4.5   4. ]
 [450.    4.5   5. ]
 [450.    4.5   7. ]
 [450.    6.5   5. ]
 [450.    6.5   4. ]
 [450.    5.5   7. ]
 [450.    6.5   9. ]
 [450.    6.5   7. ]
 [450.    6.5   8. ]
 [450.    7.5   8. ]
 [450.    7.5   7. ]
 [450.    8.5   9. ]
 [450.    8.5   4. ]
 [450.    8.5   6. ]
 [450.    7.5   5. ]
 [450.    8.5   5. ]
 [450.    8.5   7. ]
 [450.    8.5   8. ]
 [550.    3.5   4. ]
 [550.    4.5   8. ]
 [550.    4.5   9. ]
 [550.    4.5

In [77]:
print(y)

[[0.915 0.088]
 [0.903 0.1  ]
 [0.975 0.11 ]
 [1.035 0.118]
 [1.045 0.128]
 [1.158 0.135]
 [1.01  0.14 ]
 [0.975 0.143]
 [1.155 0.155]
 [1.095 0.16 ]
 [1.215 0.18 ]
 [1.195 0.188]
 [1.075 0.19 ]
 [1.18  0.193]
 [0.995 0.195]
 [0.933 0.2  ]
 [0.945 0.2  ]
 [0.958 0.208]
 [0.99  0.215]
 [0.96  0.215]
 [1.13  0.098]
 [1.163 0.103]
 [1.04  0.11 ]
 [1.2   0.11 ]
 [1.188 0.12 ]
 [1.118 0.12 ]
 [1.168 0.123]
 [1.14  0.133]
 [1.18  0.135]
 [1.043 0.143]
 [1.218 0.148]
 [1.128 0.16 ]
 [1.148 0.168]
 [1.153 0.175]
 [1.078 0.178]
 [1.08  0.178]
 [1.225 0.18 ]
 [1.153 0.195]
 [1.253 0.223]
 [1.048 0.223]
 [1.198 0.243]
 [1.113 0.245]
 [1.083 0.245]
 [1.073 0.255]
 [1.388 0.12 ]
 [1.29  0.14 ]
 [1.293 0.145]
 [1.155 0.155]
 [1.198 0.158]
 [1.305 0.16 ]
 [1.383 0.165]
 [1.208 0.175]
 [1.373 0.175]
 [1.5   0.178]
 [1.098 0.213]
 [1.183 0.223]
 [1.21  0.233]
 [1.08  0.243]
 [1.19  0.243]
 [1.198 0.268]
 [1.345 0.088]
 [1.478 0.133]
 [1.463 0.145]
 [1.353 0.175]
 [1.448 0.198]
 [1.35  0.2  ]
 [1.455 0.

In [78]:
print(xscale)

[[0.  0.4 0. ]
 [0.  0.4 0.4]
 [0.  0.4 0.8]
 [0.  0.2 0.4]
 [0.  0.4 1. ]
 [0.  0.  0. ]
 [0.  0.6 1. ]
 [0.  0.2 0.6]
 [0.  0.  0.2]
 [0.  0.6 0.4]
 [0.  0.  0.6]
 [0.  0.  0.8]
 [0.  1.  1. ]
 [0.  0.  1. ]
 [0.  0.8 1. ]
 [0.  0.8 0.6]
 [0.  0.8 0.8]
 [0.  0.8 0.4]
 [0.  1.  0.2]
 [0.  1.  0.6]
 [0.2 0.  0. ]
 [0.2 0.  0.6]
 [0.2 0.2 1. ]
 [0.2 0.4 1. ]
 [0.2 0.  0.8]
 [0.2 0.4 0. ]
 [0.2 0.2 0. ]
 [0.2 0.2 0.2]
 [0.2 0.2 0.6]
 [0.2 0.6 0.2]
 [0.2 0.6 0. ]
 [0.2 0.4 0.6]
 [0.2 0.6 1. ]
 [0.2 0.6 0.6]
 [0.2 0.6 0.8]
 [0.2 0.8 0.8]
 [0.2 0.8 0.6]
 [0.2 1.  1. ]
 [0.2 1.  0. ]
 [0.2 1.  0.4]
 [0.2 0.8 0.2]
 [0.2 1.  0.2]
 [0.2 1.  0.6]
 [0.2 1.  0.8]
 [0.4 0.  0. ]
 [0.4 0.2 0.8]
 [0.4 0.2 1. ]
 [0.4 0.2 0.4]
 [0.4 0.4 0.6]
 [0.4 0.2 0.6]
 [0.4 0.2 0.2]
 [0.4 0.4 1. ]
 [0.4 0.6 0. ]
 [0.4 0.6 0.2]
 [0.4 0.8 0.8]
 [0.4 0.8 0.4]
 [0.4 0.8 0.6]
 [0.4 1.  0.4]
 [0.4 1.  1. ]
 [0.4 1.  0.8]
 [0.6 0.  0.2]
 [0.6 0.  0.6]
 [0.6 0.  1. ]
 [0.6 0.2 0.2]
 [0.6 0.4 0.4]
 [0.6 0.4 0.8]
 [0.6 0.4 

In [79]:
print(yscale)

[[0.01333333 0.        ]
 [0.         0.0375    ]
 [0.08       0.06875   ]
 [0.14666667 0.09375   ]
 [0.15777778 0.125     ]
 [0.28333333 0.146875  ]
 [0.11888889 0.1625    ]
 [0.08       0.171875  ]
 [0.28       0.209375  ]
 [0.21333333 0.225     ]
 [0.34666667 0.2875    ]
 [0.32444444 0.3125    ]
 [0.19111111 0.31875   ]
 [0.30777778 0.328125  ]
 [0.10222222 0.334375  ]
 [0.03333333 0.35      ]
 [0.04666667 0.35      ]
 [0.06111111 0.375     ]
 [0.09666667 0.396875  ]
 [0.06333333 0.396875  ]
 [0.25222222 0.03125   ]
 [0.28888889 0.046875  ]
 [0.15222222 0.06875   ]
 [0.33       0.06875   ]
 [0.31666667 0.1       ]
 [0.23888889 0.1       ]
 [0.29444444 0.109375  ]
 [0.26333333 0.140625  ]
 [0.30777778 0.146875  ]
 [0.15555556 0.171875  ]
 [0.35       0.1875    ]
 [0.25       0.225     ]
 [0.27222222 0.25      ]
 [0.27777778 0.271875  ]
 [0.19444444 0.28125   ]
 [0.19666667 0.28125   ]
 [0.35777778 0.2875    ]
 [0.27777778 0.334375  ]
 [0.38888889 0.421875  ]
 [0.16111111 0.421875  ]


In [80]:
X_train, X_test, y_train, y_test = train_test_split(xscale, yscale)

In [81]:
model = Sequential()
model.add(Dense(12, input_dim=3, kernel_initializer='normal', activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='linear'))
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_24 (Dense)             (None, 12)                48        
_________________________________________________________________
dense_25 (Dense)             (None, 8)                 104       
_________________________________________________________________
dense_26 (Dense)             (None, 1)                 9         
Total params: 161
Trainable params: 161
Non-trainable params: 0
_________________________________________________________________


In [82]:
model.compile(loss='mse', optimizer='adam', metrics=['mse','mae'])

In [83]:
>>> history = model.fit(X_train, y_train, epochs=150, batch_size=50,  verbose=1, validation_split=0.2)

ValueError: A target array with shape (75, 2) was passed for an output of shape (None, 1) while using as loss `mean_squared_error`. This loss expects targets to have the same shape as the output.