In [1]:
from scipy import io
import numpy as np

In [2]:
X = io.loadmat('origin_X.mat')
Y = io.loadmat('origin_Y.mat')

In [3]:
Data_X = X['X']
Data_Y = Y['Y']

In [4]:
import pandas as pd

In [5]:
Data_X = pd.DataFrame(Data_X)
Data_Y = pd.DataFrame(Data_Y)

In [6]:
Label = pd.DataFrame(-np.ones(np.shape(Data_Y)))

In [7]:
Label.loc[Data_Y[0] != 5] = 1

In [8]:
import math

In [9]:
num_folds = 10
subset_size = math.trunc(len(Data_X)/num_folds)

In [10]:
subset_size

5920

In [11]:
Data_X = np.array(Data_X)
Label = np.array(Label)

In [12]:
from sklearn.model_selection import KFold

In [13]:
kf = KFold(n_splits=10)

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
confu_mat = list()

In [17]:
for train_index, test_index in kf.split(Data_X):
    X_train, X_test = Data_X[train_index], Data_X[test_index]
    y_train, y_test = Label[train_index], Label[test_index]
    y_train = np.ravel(y_train)
    
    clf = LogisticRegression(solver='newton-cg',class_weight='balanced')
    clf.fit(X_train, y_train)
    
    y_pred = clf.predict(X_test)
    score  = clf.score(X_test, y_test)
    print(score)
    
    conmat = confusion_matrix(y_test, y_pred)
    confu_mat.append(conmat)
    print(conmat)

0.528458030738051
[[2809 2547]
 [ 245  320]]
0.5679783820300625
[[3092 2319]
 [ 239  271]]
0.5544671508191183
[[2979 2397]
 [ 241  304]]
0.5465293024826887
[[2915 2451]
 [ 234  321]]
0.5178179361594325
[[2766 2635]
 [ 220  300]]
0.5540540540540541
[[2986 2399]
 [ 241  294]]
0.579222972972973
[[3119 2241]
 [ 250  310]]
0.5070945945945946
[[2698 2702]
 [ 216  304]]
0.5641891891891891
[[3040 2340]
 [ 240  300]]
0.543581081081081
[[2894 2476]
 [ 226  324]]


In [18]:
sum_confu = sum(confu_mat)

In [19]:
specificity = sum_confu[0,0] / (sum_confu[0,0]+sum_confu[0,1])
sensitivity = sum_confu[1,1] / (sum_confu[1,1]+sum_confu[1,0])

In [20]:
print('specificity: {0}, sensitivity: {1}'.format(specificity,sensitivity))

specificity: 0.5445218845832172, sensitivity: 0.5644444444444444


In [ ]:
sum