In [1]:
from scipy import io
import numpy as np

In [2]:
X = io.loadmat('origin_X.mat')
Y = io.loadmat('origin_Y.mat')

In [3]:
Data_X = X['X']
Data_Y = Y['Y']

In [4]:
import pandas as pd

In [5]:
Data_X = pd.DataFrame(Data_X)
Data_Y = pd.DataFrame(Data_Y)

In [6]:
Label = pd.DataFrame(-np.ones(np.shape(Data_Y)))

In [7]:
Label.loc[Data_Y[0] != 5] = 1

In [8]:
import math

In [9]:
num_folds = 10
subset_size = math.trunc(len(Data_X)/num_folds)

In [10]:
subset_size

5920

In [11]:
Data_X = np.array(Data_X)
Label = np.array(Label)

In [12]:
from sklearn.model_selection import KFold

In [13]:
kf = KFold(n_splits=10)

In [14]:
from sklearn.naive_bayes import GaussianNB

In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
confu_mat = list()

In [17]:
for train_index, test_index in kf.split(Data_X):
    X_train, X_test = Data_X[train_index], Data_X[test_index]
    y_train, y_test = Label[train_index], Label[test_index]
    y_train = np.ravel(y_train)
    
    clf = GaussianNB()
    clf.fit(X_train, y_train)
    
    y_pred = clf.predict(X_test)
    score  = clf.score(X_test, y_test)
    print(score)
    
    conmat = confusion_matrix(y_test, y_pred)
    confu_mat.append(conmat)
    print(conmat)

0.9045769295727073
[[5356    0]
 [ 565    0]]
0.9138659010302314
[[5411    0]
 [ 510    0]]
0.9079547373754433
[[5376    0]
 [ 545    0]]
0.9062658334740753
[[5366    0]
 [ 555    0]]
0.9121769971288634
[[5401    0]
 [ 520    0]]
0.9096283783783784
[[5385    0]
 [ 535    0]]
0.9054054054054054
[[5360    0]
 [ 560    0]]
0.9121621621621622
[[5400    0]
 [ 520    0]]
0.9087837837837838
[[5380    0]
 [ 540    0]]
0.9070945945945946
[[5370    0]
 [ 550    0]]


In [18]:
sum_confu = sum(confu_mat)

In [19]:
specificity = sum_confu[0,0] / (sum_confu[0,0]+sum_confu[0,1])
sensitivity = sum_confu[1,1] / (sum_confu[1,1]+sum_confu[1,0])

In [20]:
print('specificity: {0}, sensitivity: {1}'.format(specificity,sensitivity))

specificity: 1.0, sensitivity: 0.0


In [21]:
sum_confu

array([[53805,     0],
       [ 5400,     0]])